apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-db-secret
  namespace: linkding
  labels:
    app: linkding
    component: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: linkding-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: linkding-postgres
        property: admin_username
    - secretKey: password
      remoteRef:
        key: linkding-postgres
        property: admin_password

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-user-password
  namespace: linkding
  labels:
    app: linkding
    component: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: linkding-user-password
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: linkding-postgres
        property: app_username
    - secretKey: password
      remoteRef:
        key: linkding-postgres
        property: app_password