apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-unseal
  namespace: vault
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: vault-unseal
          initContainers:
          - name: wait-for-init
            image: alpine:3.22
            command:
            - /bin/sh
            - -c
            - |

              # Install required tools
              echo "Installing required tools"
              apk add --no-cache kubectl

              echo "Waiting for vault-unseal-keys secret..."
              until kubectl get secret vault-unseal-keys -n vault > /dev/null 2>&1; do
                echo "Waiting for Vault to be initialized..."
                sleep 10
              done
              echo "Vault initialization confirmed!"
          containers:
          - name: unseal
            image: alpine:3.22
            command:
            - /bin/sh
            - -c
            - |

              # Install required tools
              echo "Installing required tools"
              apk add --no-cache wget unzip jq

              # Install vault CLI
              echo "Installing Vault CLI"
              wget https://releases.hashicorp.com/vault/1.17.2/vault_1.17.2_linux_amd64.zip
              unzip vault_1.17.2_linux_amd64.zip
              mv vault /usr/local/bin/
              chmod +x /usr/local/bin/vault

              echo "Vault Installed"

              for i in 0 1; do
                STATUS=$(vault status -address=http://vault-$i.vault-internal:8200 -format=json | jq -r '.sealed')
                echo "Vault-$i status : $STATUS"
                if [ "$STATUS" = "true" ]; then
                  echo "Unsealing vault-$i"
                  vault operator unseal -address=http://vault-$i.vault-internal:8200 $KEY_1
                  vault operator unseal -address=http://vault-$i.vault-internal:8200 $KEY_2
                  vault operator unseal -address=http://vault-$i.vault-internal:8200 $KEY_3
                else
                  echo "vault-$i is already unsealed"
                fi
              done
            envFrom:
            - secretRef:
                name: vault-unseal-keys
          restartPolicy: OnFailure