apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
  namespace: vault
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: vault-init
      initContainers:
      - name: wait-for-vault
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z vault.vault.svc.cluster.local 8200; do echo "Waiting for Vault..."; sleep 5; done']
      containers:
      - name: vault-init
        image: alpine:3.22
        command:
        - /bin/sh
        - -c
        - |
          
          # Install required tools
          echo "Installing required tools"
          apk add --no-cache wget unzip jq openssl kubectl

          # Install vault CLI
          echo "Installing Vault CLI"
          wget https://releases.hashicorp.com/vault/1.17.2/vault_1.17.2_linux_amd64.zip
          unzip vault_1.17.2_linux_amd64.zip
          mv vault /usr/local/bin/
          chmod +x /usr/local/bin/vault

          echo "Vault Installed"

          STATUS=$(vault status -address=http://vault-0.vault-internal:8200 -format=json | jq -r '.initialized')

          echo "Status : $STATUS"

          if [ "$STATUS" = "false" ]; then
          echo "Initializing vault-0"
          vault operator init -key-shares=5 -key-threshold=3 -address=http://vault-0.vault-internal:8200 -format=json > /tmp/init.json

          echo "Vault Init"

          KEY_1=$(jq -r '.unseal_keys_b64[0]' /tmp/init.json)
          KEY_2=$(jq -r '.unseal_keys_b64[1]' /tmp/init.json)
          KEY_3=$(jq -r '.unseal_keys_b64[2]' /tmp/init.json)
          KEY_4=$(jq -r '.unseal_keys_b64[3]' /tmp/init.json)
          KEY_5=$(jq -r '.unseal_keys_b64[4]' /tmp/init.json)
          ROOT_TOKEN=$(jq -r '.root_token' /tmp/init.json)

          echo "Keys Retrieved"

          # Create secret with unseal keys
          echo "Creating Secret with Unseal Keys"
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Secret
          metadata:
            name: vault-unseal-keys
            namespace: vault
          type: Opaque
          data:
            KEY_1: $(echo -n "${KEY_1}" | base64 -w 0)
            KEY_2: $(echo -n "${KEY_2}" | base64 -w 0)
            KEY_3: $(echo -n "${KEY_3}" | base64 -w 0)
            KEY_4: $(echo -n "${KEY_4}" | base64 -w 0)
            KEY_5: $(echo -n "${KEY_5}" | base64 -w 0)
            ROOT_TOKEN: $(echo -n "${ROOT_TOKEN}" | base64 -w 0)
          EOF
          # Clean up
          rm -f /tmp/init.json
          exit 0
          else
          echo "vault-0 is already initialized"
          exit 0
          fi
          