apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: task-queue-worker-secrets
  namespace: task-queue-worker
spec:
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: ghcr-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: task-queue-worker
        property: ghcr-token