apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      securityContext:
        runAsUser: 5050
        runAsGroup: 5050
        fsGroup: 5050
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:8.2
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: test@test.com
          #valueFrom:
          #  secretKeyRef:
          #    name: pgadmin-credentials
          #    key: default-email
        - name: PGADMIN_DEFAULT_PASSWORD
          value: test
          #valueFrom:
          #  secretKeyRef:
          #    name: pgadmin-credentials
          #    key: default-password
        - name: PGADMIN_LISTEN_PORT
          value: "8080"
        - name: PGADMIN_LISTEN_ADDRESS
          value: "0.0.0.0"
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /misc/ping
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /misc/ping
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        securityContext:
            allowPrivilegeEscalation: false
      volumes:
      - name: pgadmin-data
        persistentVolumeClaim:
          claimName: pgadmin-pvc