apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-credentials
  namespace: pgadmin
spec:
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: pgadmin-credentials
    creationPolicy: Owner
  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: pgadmin
        property: pgadmin-email
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: pgadmin
        property: pgadmin-password