apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-credentials
  namespace: pgadmin
spec:
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm-secret-store
  target:
    name: pgadmin-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: pgadmin-app