apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-secrets
  namespace: linkding
spec:
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: linkding-secrets
    creationPolicy: Owner
  data:
    - secretKey: LD_SUPERUSER_NAME
      remoteRef:
        key: linkding
        property: superuser_name
    - secretKey: LD_SUPERUSER_PASSWORD
      remoteRef:
        key: linkding
        property: superuser_password
    # DB Creds
    - secretKey: LD_DB_USER
      remoteRef:
        key: linkding-postgres
        property: app_username
    - secretKey: LD_DB_PASSWORD
      remoteRef:
        key: linkding-postgres
        property: app_password