apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-pvc
  namespace: linkding
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: piraeus-storage
  resources:
    requests:
      storage: 1Gi